### ISSUE TITLE
Adding CNR receiver hei_id to the request parameters and making it required

### ISSUE THREAD

**Issue by spetronnetworks** [erasmus-without-paper/ewp-specs-api-iia-cnr#1]
Hello,

REF: https://github.com/erasmus-without-paper/ewp-specs-api-iia-cnr#request-parameters

A CNR request currently has only 2 parameters as follows:
- notifier_hei_id (required)
- iia_id (required)

I think that there must be a third parameter as the CNR receiver hei_id 
This is for the HEI that receives the CNR or in other words, the HEI, to whom the CNR is being sent.

The lack of this parameter causes problems and inconvenience especially when you are a provider and you cover more than one HEI in one domain.
You do not know to whom to deliver the received CNR. 
And therefore, you need to fetch the IIA via get-api and find out the partner and then deliver it to the partner.

It is something like an Amazon package which the cargo staff does not know to which number/flat to deliver it in a building that has many families living there. S/he need to open the package and check the content and find out which flat number!

And this issue is available in all other API CNRs. 
[And also in IIA-INDEX API, too, where the partner hei id is optional and on its absence, we need to check signature and match it from the catalogue to find out requester HEIs)]

Hope I made it clear. If not, please do not hesitate to ask for more clarification.

**Comment by janinamincer-daszkiewicz** [comment]
See: https://github.com/erasmus-without-paper/ewp-specs-api-omobility-cnr/issues/2

**Comment by muratyuceer** [comment]
Hi, we have same problem

**Comment by janinamincer-daszkiewicz** [comment]
Discovery 6.0.0 solves the problem.
